services:

  my-ocr-tesseract:
    image: ocr-app-cpu:dev
    build:
      context: .
      dockerfile: Dockerfile-cpu
    container_name: my-ocr-tesseract
    ports:
      - "8010:8080"
    command: >
      uvicorn app.api.routes-tesseract:app
      --host 0.0.0.0
      --port 8080
      --workers 4
    restart: unless-stopped

  my-ocr-deepseek:
    image: ocr-app-gpu:dev
    build:
      context: .
      dockerfile: Dockerfile-gpu
    container_name: my-ocr-deepseek
    ports:
      - "8020:8080"
    command: >
      uvicorn app.api.routes-deepseek:app
      --host 0.0.0.0
      --port 8080
      --workers 1
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    restart: unless-stopped
