services:
  my-ocr-tesseract:
    image: ocr-app:dev
    build:
      path: .
      dockerfile: Dockerfile
    container_name: my-ocr-tesseract
    ports:
      - "8000:8080"
    command: >
      uvicorn app.api.routes-tesseract:app
      --host 0.0.0.0
      --port 8080
      --workers 4
    restart: unless-stopped
